export const CREATE_TODO_START = 'CREATE_TODO_START';
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';
export const CREATE_TODO_FAIL = 'CREATE_TODO_FAIL';

export const FETCH_TODOS_START = 'FETCH_TODOS_START';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_FAIL = 'FETCH_TODOS_FAIL';

export const SAVE_LIST_NAME_START = 'SAVE_LIST_NAME_START';
export const SAVE_LIST_NAME_SUCCESS = 'SAVE_LIST_NAME_SUCCESS';
export const SAVE_LIST_NAME_FAIL = 'SAVE_LIST_NAME_FAIL';

export const DELETE_LIST_NAME_START = 'DELETE_LIST_NAME_START';
export const DELETE_LIST_NAME_FAIL = 'DELETE_LIST_NAME_FAIL';

export const FETCH_LIST_NAMES_SUCCESS = 'FETCH_LIST_NAMES_SUCCESS';
export const FETCH_LIST_NAMES_FAIL = 'FETCH_LIST_NAMES_FAIL';

export const DELETE_TODO_START = 'DELETE_TODO_START';
export const DELETE_TODO_FAIL = 'DELETE_TODO_FAIL';

export const UPDATE_TODO_START = 'UPDATE_TODO_START';
export const UPDATE_TODO_FAIL = 'UPDATE_TODO_FAIL';

export const AUTH_START = 'AUTH_LOGIN_START';
export const AUTH_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SHOW_DRAWER = 'SHOW_DRAWER';
export const HIDE_DRAWER = 'HIDE_DRAWER';
